<head>
<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>css/reportingforms.css" />
</head>
<br />
<h3>Edit a Record</h3><br />
<?php echo form_open('reportingforms/edit_validate/'.$row->id); ?>
<div class="control-group"><label>Week no: </label><div class="controls"><?php $data = array('id' => 'week_no', 'name' => 'week_no', 'value' => $row->week_no); echo form_input($data, set_value('week_no')); ?></div>
</div><div class="control-group"><label>Reporting year: </label><div class="controls"><?php $data = array('id' => 'reporting_year', 'name' => 'reporting_year', 'value' => $row->reporting_year); echo form_input($data, set_value('reporting_year')); ?></div>
</div><div class="control-group"><label>Reporting date: </label><div class="controls"><?php $data = array('id' => 'reporting_date', 'name' => 'reporting_date', 'value' => $row->reporting_date); echo form_input($data, set_value('reporting_date')); ?></div>
</div><div class="control-group"><label>User id: </label><div class="controls"><?php $data = array('id' => 'user_id', 'name' => 'user_id', 'value' => $row->user_id); echo form_input($data, set_value('user_id')); ?></div>
</div><div class="control-group"><label>Healthfacility id: </label><div class="controls"><?php $data = array('id' => 'healthfacility_id', 'name' => 'healthfacility_id', 'value' => $row->healthfacility_id); echo form_input($data, set_value('healthfacility_id')); ?></div>
</div><div class="control-group"><label>Contact number: </label><div class="controls"><?php $data = array('id' => 'contact_number', 'name' => 'contact_number', 'value' => $row->contact_number); echo form_input($data, set_value('contact_number')); ?></div>
</div><div class="control-group"><label>Health facility code: </label><div class="controls"><?php $data = array('id' => 'health_facility_code', 'name' => 'health_facility_code', 'value' => $row->health_facility_code); echo form_input($data, set_value('health_facility_code')); ?></div>
</div><div class="control-group"><label>Supporting ngo: </label><div class="controls"><?php $data = array('id' => 'supporting_ngo', 'name' => 'supporting_ngo', 'value' => $row->supporting_ngo); echo form_input($data, set_value('supporting_ngo')); ?></div>
</div><div class="control-group"><label>Region id: </label><div class="controls"><?php $data = array('id' => 'region_id', 'name' => 'region_id', 'value' => $row->region_id); echo form_input($data, set_value('region_id')); ?></div>
</div><div class="control-group"><label>Sariufivemale: </label><div class="controls"><?php $data = array('id' => 'sariufivemale', 'name' => 'sariufivemale', 'value' => $row->sariufivemale); echo form_input($data, set_value('sariufivemale')); ?></div>
</div><div class="control-group"><label>Sariufivefemale: </label><div class="controls"><?php $data = array('id' => 'sariufivefemale', 'name' => 'sariufivefemale', 'value' => $row->sariufivefemale); echo form_input($data, set_value('sariufivefemale')); ?></div>
</div><div class="control-group"><label>Sariofivemale: </label><div class="controls"><?php $data = array('id' => 'sariofivemale', 'name' => 'sariofivemale', 'value' => $row->sariofivemale); echo form_input($data, set_value('sariofivemale')); ?></div>
</div><div class="control-group"><label>Sariofivefemale: </label><div class="controls"><?php $data = array('id' => 'sariofivefemale', 'name' => 'sariofivefemale', 'value' => $row->sariofivefemale); echo form_input($data, set_value('sariofivefemale')); ?></div>
</div><div class="control-group"><label>Iliufivemale: </label><div class="controls"><?php $data = array('id' => 'iliufivemale', 'name' => 'iliufivemale', 'value' => $row->iliufivemale); echo form_input($data, set_value('iliufivemale')); ?></div>
</div><div class="control-group"><label>Iliufivefemale: </label><div class="controls"><?php $data = array('id' => 'iliufivefemale', 'name' => 'iliufivefemale', 'value' => $row->iliufivefemale); echo form_input($data, set_value('iliufivefemale')); ?></div>
</div><div class="control-group"><label>Awdufivemale: </label><div class="controls"><?php $data = array('id' => 'awdufivemale', 'name' => 'awdufivemale', 'value' => $row->awdufivemale); echo form_input($data, set_value('awdufivemale')); ?></div>
</div><div class="control-group"><label>Awdufivefemale: </label><div class="controls"><?php $data = array('id' => 'awdufivefemale', 'name' => 'awdufivefemale', 'value' => $row->awdufivefemale); echo form_input($data, set_value('awdufivefemale')); ?></div>
</div><div class="control-group"><label>Awdofivemale: </label><div class="controls"><?php $data = array('id' => 'awdofivemale', 'name' => 'awdofivemale', 'value' => $row->awdofivemale); echo form_input($data, set_value('awdofivemale')); ?></div>
</div><div class="control-group"><label>Awdofivefemale: </label><div class="controls"><?php $data = array('id' => 'awdofivefemale', 'name' => 'awdofivefemale', 'value' => $row->awdofivefemale); echo form_input($data, set_value('awdofivefemale')); ?></div>
</div><div class="control-group"><label>Bdufivemale: </label><div class="controls"><?php $data = array('id' => 'bdufivemale', 'name' => 'bdufivemale', 'value' => $row->bdufivemale); echo form_input($data, set_value('bdufivemale')); ?></div>
</div><div class="control-group"><label>Bdufivefemale: </label><div class="controls"><?php $data = array('id' => 'bdufivefemale', 'name' => 'bdufivefemale', 'value' => $row->bdufivefemale); echo form_input($data, set_value('bdufivefemale')); ?></div>
</div><div class="control-group"><label>Bdofivemale: </label><div class="controls"><?php $data = array('id' => 'bdofivemale', 'name' => 'bdofivemale', 'value' => $row->bdofivemale); echo form_input($data, set_value('bdofivemale')); ?></div>
</div><div class="control-group"><label>Bdofivefemale: </label><div class="controls"><?php $data = array('id' => 'bdofivefemale', 'name' => 'bdofivefemale', 'value' => $row->bdofivefemale); echo form_input($data, set_value('bdofivefemale')); ?></div>
</div><div class="control-group"><label>Oadufivemale: </label><div class="controls"><?php $data = array('id' => 'oadufivemale', 'name' => 'oadufivemale', 'value' => $row->oadufivemale); echo form_input($data, set_value('oadufivemale')); ?></div>
</div><div class="control-group"><label>Oadufivefemale: </label><div class="controls"><?php $data = array('id' => 'oadufivefemale', 'name' => 'oadufivefemale', 'value' => $row->oadufivefemale); echo form_input($data, set_value('oadufivefemale')); ?></div>
</div><div class="control-group"><label>Oadofivemale: </label><div class="controls"><?php $data = array('id' => 'oadofivemale', 'name' => 'oadofivemale', 'value' => $row->oadofivemale); echo form_input($data, set_value('oadofivemale')); ?></div>
</div><div class="control-group"><label>Oadofivefemale: </label><div class="controls"><?php $data = array('id' => 'oadofivefemale', 'name' => 'oadofivefemale', 'value' => $row->oadofivefemale); echo form_input($data, set_value('oadofivefemale')); ?></div>
</div><div class="control-group"><label>Diphmale: </label><div class="controls"><?php $data = array('id' => 'diphmale', 'name' => 'diphmale', 'value' => $row->diphmale); echo form_input($data, set_value('diphmale')); ?></div>
</div><div class="control-group"><label>Diphfemale: </label><div class="controls"><?php $data = array('id' => 'diphfemale', 'name' => 'diphfemale', 'value' => $row->diphfemale); echo form_input($data, set_value('diphfemale')); ?></div>
</div><div class="control-group"><label>Wcmale: </label><div class="controls"><?php $data = array('id' => 'wcmale', 'name' => 'wcmale', 'value' => $row->wcmale); echo form_input($data, set_value('wcmale')); ?></div>
</div><div class="control-group"><label>Wcfemale: </label><div class="controls"><?php $data = array('id' => 'wcfemale', 'name' => 'wcfemale', 'value' => $row->wcfemale); echo form_input($data, set_value('wcfemale')); ?></div>
</div><div class="control-group"><label>Measmale: </label><div class="controls"><?php $data = array('id' => 'measmale', 'name' => 'measmale', 'value' => $row->measmale); echo form_input($data, set_value('measmale')); ?></div>
</div><div class="control-group"><label>Measfemale: </label><div class="controls"><?php $data = array('id' => 'measfemale', 'name' => 'measfemale', 'value' => $row->measfemale); echo form_input($data, set_value('measfemale')); ?></div>
</div><div class="control-group"><label>Nntmale: </label><div class="controls"><?php $data = array('id' => 'nntmale', 'name' => 'nntmale', 'value' => $row->nntmale); echo form_input($data, set_value('nntmale')); ?></div>
</div><div class="control-group"><label>Nntfemale: </label><div class="controls"><?php $data = array('id' => 'nntfemale', 'name' => 'nntfemale', 'value' => $row->nntfemale); echo form_input($data, set_value('nntfemale')); ?></div>
</div><div class="control-group"><label>Afpmale: </label><div class="controls"><?php $data = array('id' => 'afpmale', 'name' => 'afpmale', 'value' => $row->afpmale); echo form_input($data, set_value('afpmale')); ?></div>
</div><div class="control-group"><label>Afpfemale: </label><div class="controls"><?php $data = array('id' => 'afpfemale', 'name' => 'afpfemale', 'value' => $row->afpfemale); echo form_input($data, set_value('afpfemale')); ?></div>
</div><div class="control-group"><label>Ajsmale: </label><div class="controls"><?php $data = array('id' => 'ajsmale', 'name' => 'ajsmale', 'value' => $row->ajsmale); echo form_input($data, set_value('ajsmale')); ?></div>
</div><div class="control-group"><label>Ajsfemale: </label><div class="controls"><?php $data = array('id' => 'ajsfemale', 'name' => 'ajsfemale', 'value' => $row->ajsfemale); echo form_input($data, set_value('ajsfemale')); ?></div>
</div><div class="control-group"><label>Vhfmale: </label><div class="controls"><?php $data = array('id' => 'vhfmale', 'name' => 'vhfmale', 'value' => $row->vhfmale); echo form_input($data, set_value('vhfmale')); ?></div>
</div><div class="control-group"><label>Vhffemale: </label><div class="controls"><?php $data = array('id' => 'vhffemale', 'name' => 'vhffemale', 'value' => $row->vhffemale); echo form_input($data, set_value('vhffemale')); ?></div>
</div><div class="control-group"><label>Malufivemale: </label><div class="controls"><?php $data = array('id' => 'malufivemale', 'name' => 'malufivemale', 'value' => $row->malufivemale); echo form_input($data, set_value('malufivemale')); ?></div>
</div><div class="control-group"><label>Malufivefemale: </label><div class="controls"><?php $data = array('id' => 'malufivefemale', 'name' => 'malufivefemale', 'value' => $row->malufivefemale); echo form_input($data, set_value('malufivefemale')); ?></div>
</div><div class="control-group"><label>Malofivemale: </label><div class="controls"><?php $data = array('id' => 'malofivemale', 'name' => 'malofivemale', 'value' => $row->malofivemale); echo form_input($data, set_value('malofivemale')); ?></div>
</div><div class="control-group"><label>Malofivefemale: </label><div class="controls"><?php $data = array('id' => 'malofivefemale', 'name' => 'malofivefemale', 'value' => $row->malofivefemale); echo form_input($data, set_value('malofivefemale')); ?></div>
</div><div class="control-group"><label>Suspectedmenegitismale: </label><div class="controls"><?php $data = array('id' => 'suspectedmenegitismale', 'name' => 'suspectedmenegitismale', 'value' => $row->suspectedmenegitismale); echo form_input($data, set_value('suspectedmenegitismale')); ?></div>
</div><div class="control-group"><label>Suspectedmenegitisfemale: </label><div class="controls"><?php $data = array('id' => 'suspectedmenegitisfemale', 'name' => 'suspectedmenegitisfemale', 'value' => $row->suspectedmenegitisfemale); echo form_input($data, set_value('suspectedmenegitisfemale')); ?></div>
</div><div class="control-group"><label>Undismale: </label><div class="controls"><?php $data = array('id' => 'undismale', 'name' => 'undismale', 'value' => $row->undismale); echo form_input($data, set_value('undismale')); ?></div>
</div><div class="control-group"><label>Undisfemale: </label><div class="controls"><?php $data = array('id' => 'undisfemale', 'name' => 'undisfemale', 'value' => $row->undisfemale); echo form_input($data, set_value('undisfemale')); ?></div>
</div><div class="control-group"><label>Ocmale: </label><div class="controls"><?php $data = array('id' => 'ocmale', 'name' => 'ocmale', 'value' => $row->ocmale); echo form_input($data, set_value('ocmale')); ?></div>
</div><div class="control-group"><label>Ocfemale: </label><div class="controls"><?php $data = array('id' => 'ocfemale', 'name' => 'ocfemale', 'value' => $row->ocfemale); echo form_input($data, set_value('ocfemale')); ?></div>
</div><div class="control-group"><label>Total consultations: </label><div class="controls"><?php $data = array('id' => 'total_consultations', 'name' => 'total_consultations', 'value' => $row->total_consultations); echo form_input($data, set_value('total_consultations')); ?></div>
</div><div class="control-group"><label>Sre: </label><div class="controls"><?php $data = array('id' => 'sre', 'name' => 'sre', 'value' => $row->sre); echo form_input($data, set_value('sre')); ?></div>
</div><div class="control-group"><label>Pf: </label><div class="controls"><?php $data = array('id' => 'pf', 'name' => 'pf', 'value' => $row->pf); echo form_input($data, set_value('pf')); ?></div>
</div><div class="control-group"><label>Pv: </label><div class="controls"><?php $data = array('id' => 'pv', 'name' => 'pv', 'value' => $row->pv); echo form_input($data, set_value('pv')); ?></div>
</div><div class="control-group"><label>Pmix: </label><div class="controls"><?php $data = array('id' => 'pmix', 'name' => 'pmix', 'value' => $row->pmix); echo form_input($data, set_value('pmix')); ?></div>
</div><div class="control-group"><label>Totalnegative: </label><div class="controls"><?php $data = array('id' => 'totalnegative', 'name' => 'totalnegative', 'value' => $row->totalnegative); echo form_input($data, set_value('totalnegative')); ?></div>
</div><div class="control-group"><label>Approved hf: </label><div class="controls"><?php $data = array('id' => 'approved_hf', 'name' => 'approved_hf', 'value' => $row->approved_hf); echo form_input($data, set_value('approved_hf')); ?></div>
</div><div class="control-group"><label>Approved regional: </label><div class="controls"><?php $data = array('id' => 'approved_regional', 'name' => 'approved_regional', 'value' => $row->approved_regional); echo form_input($data, set_value('approved_regional')); ?></div>
</div><div class="control-group"><label>Approved zone: </label><div class="controls"><?php $data = array('id' => 'approved_zone', 'name' => 'approved_zone', 'value' => $row->approved_zone); echo form_input($data, set_value('approved_zone')); ?></div>
</div><div class="form-actions"><?php echo form_submit('submit', 'Update', 'class="btn btn-info "'); ?></div>
<?php echo form_close(); ?>
<?php echo validation_errors(); ?>
<script type="text/javascript" src="<?php echo base_url() ?>js/reportingforms.js"></script>
